import { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { motion } from 'motion/react';
import * as LucideIcons from 'lucide-react';
import { getBusinessData, BusinessData } from '../data/mockBusinessData';
import NotFound from './NotFound';

// Helper to dynamically render icons
function Icon({ name, className }: { name: string; className?: string }) {
  // @ts-ignore
  const LucideIcon = LucideIcons[name] || LucideIcons.CheckCircle;
  return <LucideIcon className={className} />;
}

export default function BusinessPreview() {
  const { country, city, category, businessSlug } = useParams();
  const [data, setData] = useState<BusinessData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    getBusinessData(country, city, category, businessSlug)
      .then(res => {
        setData(res);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, [country, city, category, businessSlug]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[#0a0f1e]">
        <motion.div animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 1, ease: 'linear' }} className="w-8 h-8 rounded-full border-t-2 border-[#00e5d4] border-r-2" />
      </div>
    );
  }

  if (!data) return <NotFound />;

  const statusColors = {
    draft: 'bg-gray-500/20 text-gray-400 border-gray-500/30',
    generated: 'bg-blue-500/20 text-blue-400 border-blue-500/30',
    sent: 'bg-amber-500/20 text-amber-400 border-amber-500/30',
    viewed: 'bg-purple-500/20 text-purple-400 border-purple-500/30',
    claimed: 'bg-green-500/20 text-green-400 border-green-500/30',
    expired: 'bg-red-500/20 text-red-400 border-red-500/30',
  };

  const whatsappMessage = encodeURIComponent(`Hi, I saw the preview website for ${data.businessName} generated by NexviaTech. I would like to learn more about claiming it.`);
  const whatsappUrl = `https://wa.me/1234567890?text=${whatsappMessage}`; // Example number

  const schemaData = {
    "@context": "https://schema.org",
    "@type": "LocalBusiness",
    "name": data.businessName,
    "image": data.heroImage,
    "telephone": data.phone,
    "url": data.website,
    "address": {
      "@type": "PostalAddress",
      "addressLocality": data.city,
      "addressCountry": data.country
    }
  };

  return (
    <div className="min-h-screen bg-[#0a0f1e] text-[#f0f4f8] font-sans pb-24 md:pb-0">
      <Helmet>
        <title>{data.businessName} | Website Preview by NexviaTech</title>
        <meta name="description" content={data.aboutText.substring(0, 160)} />
        <script type="application/ld+json">{JSON.stringify(schemaData)}</script>
      </Helmet>

      {/* Preview Ribbon */}
      <div className="sticky top-0 z-[100] w-full h-10 bg-[#00e5d4]/10 border-b border-[#00e5d4]/20 flex items-center justify-between px-6 shrink-0 backdrop-blur-md">
        <div className="flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-[#00e5d4] animate-pulse"></span>
          <span className="text-[10px] md:text-[11px] uppercase tracking-widest font-bold text-[#00e5d4]">
            <span className="hidden sm:inline">Live Preview · Designed by </span>NexviaTech
          </span>
        </div>
        <a href={whatsappUrl} target="_blank" rel="noreferrer" className="text-[10px] md:text-[11px] font-bold text-[#f0f4f8] hover:text-[#00e5d4] uppercase tracking-wider transition-colors">
          Claim This Website
        </a>
      </div>

      {/* Hero Section */}
      <section className="relative px-6 py-20 md:py-32 flex flex-col items-center text-center overflow-hidden min-h-[70vh] justify-center">
        <div className="absolute inset-0 -z-20">
          <img src={data.heroImage} alt={data.businessName} className="w-full h-full object-cover opacity-20" />
          <div className="absolute inset-0 bg-[#0a0f1e]/80 mix-blend-multiply" />
        </div>
        <div className="absolute top-[-20%] left-[-10%] w-[600px] h-[600px] bg-[#00e5d4]/10 rounded-full blur-[120px] pointer-events-none -z-10"></div>
        <div className="absolute bottom-[-10%] right-[-5%] w-[400px] h-[400px] bg-blue-600/10 rounded-full blur-[100px] pointer-events-none -z-10"></div>

        <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ staggerChildren: 0.1 }} className="max-w-4xl relative z-10 w-full flex flex-col items-center">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-white/5 border border-white/10 rounded-full mb-6">
            <span className="text-[#00e5d4] text-[10px] font-bold tracking-[0.2em] uppercase">Official Preview</span>
            <span className="w-1 h-1 bg-white/30 rounded-full"></span>
            <span className="text-white/50 text-[10px] uppercase font-medium">{data.city.replace('-', ' ')}, {data.country}</span>
          </div>
          
          <h1 className="text-5xl md:text-7xl font-extrabold tracking-tighter text-white leading-[0.9] drop-shadow-lg max-w-4xl">
            {data.businessName}
          </h1>

          <p className="text-white/60 text-lg md:text-xl max-w-2xl mx-auto leading-relaxed mt-6">
            {data.tagline}
          </p>

          <div className="flex items-center justify-center gap-1 text-yellow-400 py-4">
            {[...Array(5)].map((_, i) => (
               <LucideIcons.Star key={i} size={20} fill={i < Math.floor(data.rating) ? "currentColor" : "none"} className={i >= Math.floor(data.rating) ? "text-white/30" : ""} />
            ))}
            <span className="text-white/80 font-medium ml-2 text-sm">({data.reviewCount} Reviews)</span>
          </div>

          <div className="flex flex-col sm:flex-row gap-4 justify-center pt-8 w-full sm:w-auto">
            <a href={whatsappUrl} target="_blank" rel="noreferrer" className="w-full sm:w-auto px-8 py-4 bg-green-500/20 text-green-400 border border-green-500/30 rounded-2xl font-bold flex items-center justify-center gap-2 hover:bg-green-500/30 transition-all">
              <LucideIcons.MessageCircle size={20} />
              WhatsApp Us Now
            </a>
            <a href={`tel:${data.phone}`} className="w-full sm:w-auto px-8 py-4 bg-[#00e5d4] text-[#0a0f1e] rounded-2xl font-bold uppercase tracking-wider text-sm shadow-[0_0_20px_rgba(0,229,212,0.3)] hover:shadow-[0_0_30px_rgba(0,229,212,0.5)] transition-all flex items-center justify-center gap-2">
              <LucideIcons.Phone size={20} />
              Call {data.phone}
            </a>
          </div>
        </motion.div>
      </section>

      {/* Main Content Area */}
      <div className="max-w-7xl mx-auto px-6 space-y-24 py-24">
        
        {/* Services */}
        <motion.section 
          initial="hidden" whileInView="visible" viewport={{ once: true, margin: "-100px" }}
          variants={{ hidden: { opacity: 0 }, visible: { opacity: 1, transition: { staggerChildren: 0.1 } } }}
        >
          <div className="text-center mb-12">
            <h2 className="font-display text-3xl md:text-4xl font-bold text-white mb-4">Our Services</h2>
            <div className="w-16 h-1 bg-[#00e5d4] mx-auto rounded-full mix-blend-screen" />
          </div>
          
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">
            {data.services.map((service, i) => (
              <motion.div key={i} variants={{ hidden: { opacity: 0, y: 20 }, visible: { opacity: 1, y: 0 } }} className="p-6 rounded-2xl bg-white/5 border border-white/10 backdrop-blur-sm hover:border-[#00e5d4]/40 transition-colors group cursor-default">
                <div className="text-[#00e5d4] mb-3 group-hover:scale-110 transition-transform transform origin-left">
                  <Icon name={service.icon} className="w-8 h-8" />
                </div>
                <h3 className="font-bold text-white mb-1">{service.title}</h3>
                <p className="text-white/40 text-xs leading-normal">{service.description}</p>
              </motion.div>
            ))}
          </div>
        </motion.section>

        {/* About Split Layout */}
        <motion.section 
           initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
           className="grid md:grid-cols-2 gap-12 items-center"
        >
          <div className="order-2 md:order-1 space-y-6">
            <h2 className="font-display text-3xl md:text-4xl font-bold text-white">About {data.businessName}</h2>
            <p className="text-white/70 leading-relaxed text-lg">{data.aboutText}</p>
            <ul className="space-y-3 pt-4">
              {data.reasons.map((reason, i) => (
                <li key={i} className="flex items-center gap-3 text-white/90 border-b border-white/5 pb-3">
                  <Icon name={reason.icon} className="text-[#00e5d4] flex-shrink-0" />
                  <span className="font-medium">{reason.title}</span> - <span className="text-white/50 text-sm">{reason.description}</span>
                </li>
              ))}
            </ul>
          </div>
          <div className="order-1 md:order-2 rounded-2xl overflow-hidden glass-card p-2 border-[#00e5d4]/20 relative">
             <div className="absolute inset-0 bg-[#00e5d4]/5 z-10" />
             <img src={data.heroImage} alt="About" className="w-full h-[400px] object-cover rounded-xl grayscale hover:grayscale-0 transition-all duration-700" />
          </div>
        </motion.section>

        {/* Testimonials */}
        <motion.section 
          initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }}
        >
          <h2 className="font-display text-3xl text-center font-bold text-white mb-10">What Our Clients Say</h2>
          <div className="flex gap-6 overflow-x-auto pb-8 snap-x snap-mandatory hide-scrollbars">
            {data.testimonials.map((testy, i) => (
              <div key={i} className="min-w-[300px] sm:min-w-[400px] glass-card p-8 snap-center flex-shrink-0">
                <div className="flex text-[#00e5d4] mb-4">
                  {[...Array(testy.rating)].map((_, j) => <LucideIcons.Star key={j} size={16} fill="currentColor" />)}
                </div>
                <p className="text-white/80 italic mb-6">"{testy.text}"</p>
                <div className="font-medium text-white">{testy.author}</div>
              </div>
            ))}
          </div>
        </motion.section>

        {/* Info & Map Styling updated to match Frosted Glass Theme */}
        <section className="flex flex-col md:flex-row gap-6 items-stretch">
           {/* Sidebar: Status / Info Card */}
           <div className="w-full md:w-80 flex flex-col gap-6 shrink-0">
             <div className="bg-white/5 border border-white/10 rounded-3xl p-6 backdrop-blur-xl">
               <div className="flex justify-between items-start mb-6">
                 <h4 className="text-white/50 text-[11px] font-bold uppercase tracking-widest">Preview Status</h4>
                 <span className={`px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-wide border ${statusColors[data.status]}`}>
                   {data.status}
                 </span>
               </div>
               <div className="space-y-4">
                 <div className="flex items-center gap-4">
                   <div className="w-12 h-12 bg-[#00e5d4]/10 rounded-full flex items-center justify-center text-[#00e5d4] font-bold text-lg">{data.rating.toFixed(1)}</div>
                   <div>
                     <div className="text-white font-bold">Google Rating</div>
                     <div className="text-white/40 text-xs italic">{data.reviewCount}+ Verified Reviews</div>
                   </div>
                 </div>
                 <div className="h-px bg-white/10"></div>
                 <div className="space-y-4">
                   <h5 className="text-white/70 text-xs font-bold uppercase tracking-wider">Business Hours</h5>
                   <div className="space-y-2 text-xs">
                     {data.businessHours.map((bh, i) => (
                       <div key={i} className="flex justify-between text-white/50">
                         <span>{bh.days}</span>
                         <span className="text-white/80">{bh.hours}</span>
                       </div>
                     ))}
                   </div>
                 </div>
               </div>
             </div>
           </div>
           
           {/* Contact Card */}
           <div className="flex-1 bg-[#111827] border border-white/10 rounded-3xl p-8 flex flex-col justify-between">
             <div className="mb-8">
               <h4 className="text-white font-bold text-lg mb-6">Contact Us</h4>
               <div className="flex flex-col gap-6">
                 <div className="flex items-start gap-4">
                   <div className="w-6 h-6 text-[#00e5d4] flex items-center justify-center shrink-0">
                     <LucideIcons.MapPin size={20} />
                   </div>
                   <span className="text-white/70 text-sm leading-relaxed">{data.city.toUpperCase()},<br/>{data.country.toUpperCase()}</span>
                 </div>
                 <div className="flex items-start gap-4">
                   <div className="w-6 h-6 text-[#00e5d4] flex items-center justify-center shrink-0">
                     <LucideIcons.Phone size={20} />
                   </div>
                   <span className="text-white/70 text-sm">{data.phone}</span>
                 </div>
                 <div className="flex items-start gap-4">
                   <div className="w-6 h-6 text-[#00e5d4] flex items-center justify-center shrink-0">
                     <LucideIcons.Mail size={20} />
                   </div>
                   <span className="text-white/70 text-sm">{data.email}</span>
                 </div>
               </div>
             </div>
             
             <div className="flex flex-col sm:flex-row gap-4 mt-8">
               <a href={whatsappUrl} target="_blank" rel="noreferrer" className="flex-1 py-4 bg-green-500/20 text-green-400 border border-green-500/30 rounded-2xl font-bold flex items-center justify-center gap-2 hover:bg-green-500/30 transition-colors">
                 <LucideIcons.MessageCircle size={20} />
                 WhatsApp Us
               </a>
               <button className="flex-1 py-4 bg-[#00e5d4] text-[#0a0f1e] rounded-2xl font-bold uppercase tracking-wider text-sm shadow-[0_0_20px_rgba(0,229,212,0.3)] hover:shadow-[0_0_30px_rgba(0,229,212,0.5)] transition-shadow">
                 Request Site Setup
               </button>
             </div>
           </div>
        </section>

      </div>
      
      {/* Mobile Sticky CTA */}
      <div className="md:hidden fixed bottom-0 inset-x-0 p-4 bg-[#0a0f1e]/90 backdrop-blur-md border-t border-white/10 z-50 flex gap-4">
        <a href={whatsappUrl} className="flex-1 py-3 bg-[#00e5d4] text-navy font-bold rounded-lg text-center flex items-center justify-center gap-2">
          <LucideIcons.MessageCircle size={18} /> WhatsApp
        </a>
        <a href={`tel:${data.phone}`} className="flex-1 py-3 bg-white/10 text-white font-bold rounded-lg text-center flex items-center justify-center gap-2 border border-white/20">
          <LucideIcons.Phone size={18} /> Call
        </a>
      </div>
    </div>
  );
}
